### ISSUE TITLE
Publish this package

### ISSUE THREAD

**Issue by Code-Hex** [honojs/firebase-auth#6]
I wanna publish this to npm this repository.

@yusukebe Could you check this repository is it OK or not when you have time 🙏

**Comment by yusukebe** [comment]
Yes, I'll check it later.

**Comment by yusukebe** [comment]
Hi @Code-Hex !

I've done testing it on my local environment, and it worked!

These are two small things:

1. You can replace it with your own repository URLs:
  * https://github.com/honojs/firebase-auth/blob/main/package.json#L21
  * https://github.com/honojs/firebase-auth/blob/main/package.json#L23

2. It seems this middleware works only on "*Module Worker* mode. I think it's OK because the trend is using Module Worker mode on Cloudflare Worker. but, If it's so, it should be specified in the README.

**Comment by Code-Hex** [comment]
@yusukebe I'm sorry for checking your reply is delayed :bow:

And thanks for tested!!

1. Nice catch 👍 
2. This is not only "Module Worker mode" but I didn't write a document about it. I'll add it.

**Comment by Code-Hex** [comment]
I've finished a few of the issues you pointed out.

I sent review request of #8 . If you feel OK, I'll merge and publish this 🚀

**Comment by yusukebe** [comment]
Hi @Code-Hex !

I've approved your PR. Let's ship it!

**Comment by Code-Hex** [comment]
@yusukebe Thank you for everything!

**Comment by Code-Hex** [comment]
@yusukebe I've just published as 1.0.0!

https://www.npmjs.com/package/@honojs/firebase-auth

Close this issue. Thanks!!
